"""wizard_cmd.py — ``promptgenie wizard`` guided prompt builder.

A step-by-step interactive wizard that collects answers to standard prompt
engineering questions and produces:
  1. A rendered Markdown prompt file
  2. A reusable .promptgenie.yaml PromptSpec

The wizard runs entirely in the terminal using Click prompts — no Textual
dependency required.

Steps
-----
  1. Objective       — one-sentence goal
  2. Scope           — what the AI should and shouldn't touch
  3. Out-of-scope    — explicit exclusions
  4. Forbidden       — things the AI must never do
  5. Output format   — markdown / JSON / bullet list / code / etc.
  6. Verification    — how the caller will know the output is correct
  7. Target          — code-review / refactor / documentation / etc.
  8. Context packs   — select from available packs

Examples
--------
  promptgenie wizard
  promptgenie wizard --out my-prompt.md
  promptgenie wizard --no-spec   # only Markdown, skip spec generation
"""

from __future__ import annotations

import sys
from pathlib import Path

import click

from promptgenie.core.errors import EXIT_OK, EXIT_USAGE
from promptgenie.renderers.rich import console, diag_console


_PROMPT_TEMPLATE = """\
# Prompt: {objective}

## Objective
{objective}

## Scope
{scope}

## Out of Scope
{out_of_scope}

## Constraints / Forbidden Actions
{forbidden}

## Expected Output Format
{output_format}

## Verification / Acceptance Criteria
{verification}
"""

_SPEC_TEMPLATE = """\
# PromptSpec generated by promptgenie wizard
name: {name}
description: "{objective}"
prompt: {prompt_file}
provider: {provider}
model: {model}

vars: {{}}
"""


@click.command("wizard")
@click.option("--out", "out_file", default=None, help="Output path for the Markdown prompt.")
@click.option("--spec-out", default=None, help="Output path for the PromptSpec YAML.")
@click.option("--no-spec", is_flag=True, help="Skip PromptSpec generation.")
@click.option("--provider", default="claude", show_default=True)
@click.option("--model", default="claude-haiku-4-5", show_default=True)
def wizard_cmd(
    out_file: str | None,
    spec_out: str | None,
    no_spec: bool,
    provider: str,
    model: str,
) -> None:
    """Interactive guided prompt builder.

    Walks through standard prompt engineering sections and produces a
    Markdown prompt file and an optional PromptSpec YAML.

    \b
    Example:
      promptgenie wizard --out prompts/auth.md
    """
    console.print("[bold cyan]PromptGenie Wizard[/bold cyan]  — guided prompt builder\n")

    # ── Step 1: Objective ─────────────────────────────────────────────────
    console.rule("[dim]Step 1: Objective[/dim]")
    objective = click.prompt(
        "What is the one-sentence goal of this prompt?\n>",
        default="",
    ).strip()
    if not objective:
        diag_console.print("[red]Error:[/red] Objective is required.")
        raise SystemExit(EXIT_USAGE)

    # ── Step 2: Scope ─────────────────────────────────────────────────────
    console.rule("[dim]Step 2: Scope[/dim]")
    scope = click.prompt(
        "What should the AI work on / have access to?\n>",
        default="The full repository unless otherwise specified.",
    ).strip()

    # ── Step 3: Out-of-scope ──────────────────────────────────────────────
    console.rule("[dim]Step 3: Out of Scope[/dim]")
    out_of_scope = click.prompt(
        "What is explicitly out of scope?\n>",
        default="Production deployments, secrets, external API calls.",
    ).strip()

    # ── Step 4: Forbidden ────────────────────────────────────────────────
    console.rule("[dim]Step 4: Forbidden Actions[/dim]")
    forbidden = click.prompt(
        "What must the AI never do?\n>",
        default="Modify production configs, delete files, expose credentials.",
    ).strip()

    # ── Step 5: Output format ─────────────────────────────────────────────
    console.rule("[dim]Step 5: Output Format[/dim]")
    fmt_choices = ["markdown", "json", "bullet-list", "code", "plain-text", "other"]
    console.print("Options: " + ", ".join(fmt_choices))
    output_format = click.prompt("Output format", default="markdown").strip()

    # ── Step 6: Verification ──────────────────────────────────────────────
    console.rule("[dim]Step 6: Verification / Acceptance Criteria[/dim]")
    verification = click.prompt(
        "How will you verify the output is correct?\n>",
        default="Manual review + automated tests pass.",
    ).strip()

    # ── Step 7: Target ────────────────────────────────────────────────────
    console.rule("[dim]Step 7: Target Profile[/dim]")
    target_choices = ["code-review", "refactor", "documentation", "security", "testing", "custom"]
    console.print("Options: " + ", ".join(target_choices))
    target = click.prompt("Target profile", default="code-review").strip()

    # ── Step 8: Context packs ─────────────────────────────────────────────
    console.rule("[dim]Step 8: Context Packs[/dim]")
    try:
        from promptgenie.core.context_packs import list_packs
        packs = list_packs()
        pack_ids = [p["id"] for p in packs]
    except Exception:
        pack_ids = []

    selected_packs: list[str] = []
    if pack_ids:
        console.print(f"Available packs: {', '.join(pack_ids[:10])}")
        raw = click.prompt(
            "Enter pack IDs to include (comma-separated, or blank for none)",
            default="",
        ).strip()
        if raw:
            selected_packs = [p.strip() for p in raw.split(",") if p.strip()]
    else:
        console.print("[dim]No packs available.[/dim]")

    # ── Render Markdown ───────────────────────────────────────────────────
    console.rule()
    rendered = _PROMPT_TEMPLATE.format(
        objective=objective,
        scope=scope,
        out_of_scope=out_of_scope,
        forbidden=forbidden,
        output_format=output_format,
        verification=verification,
    )
    if selected_packs:
        pack_block = "\n## Context Packs\n" + "\n".join(f"- {p}" for p in selected_packs)
        rendered += pack_block

    # ── Write prompt file ─────────────────────────────────────────────────
    import re
    safe_name = re.sub(r"[^\w\-]", "-", objective[:40].lower()).strip("-")
    if out_file is None:
        out_file = f"prompts/{safe_name}.md"

    prompt_path = Path(out_file)
    prompt_path.parent.mkdir(parents=True, exist_ok=True)
    prompt_path.write_text(rendered, encoding="utf-8")
    console.print(f"[green]✓[/green] Prompt saved to [bold]{prompt_path}[/bold]")

    # ── Write PromptSpec ──────────────────────────────────────────────────
    if not no_spec:
        spec_content = _SPEC_TEMPLATE.format(
            name=safe_name,
            objective=objective,
            prompt_file=str(prompt_path),
            provider=provider,
            model=model,
        )
        spec_path_str = spec_out or f"specs/{safe_name}.yaml"
        spec_path = Path(spec_path_str)
        spec_path.parent.mkdir(parents=True, exist_ok=True)
        spec_path.write_text(spec_content, encoding="utf-8")
        console.print(f"[green]✓[/green] PromptSpec saved to [bold]{spec_path}[/bold]")

    console.print(f"\n[dim]Next steps:[/dim]")
    console.print(f"  promptgenie lint {prompt_path}")
    console.print(f"  promptgenie scan {prompt_path}")
    if not no_spec:
        console.print(f"  promptgenie run {spec_path_str}")

    raise SystemExit(EXIT_OK)
